[package]
name = "gpmf-rs"
version = "0.1.0"
authors = ["Nat Zimmermann <nat@ntzm.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
chrono = "0.4.19"
